config/routes.rb
Rails.application.routes.draw do
  resources :urls
  get "shortened/:short_url", to: "shortened_url#shortened", as: :shortened
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/shortened_url_controller.rb
# frozen_string_literal: true

class ShortenedUrlController < ApplicationController
  def shortened
    shortened_url = shortened_url_service.get_shortened_url(short_url: params[:short_url])
    redirect_to shortened_url, allow_other_host: true
  end

  def shortened_url_service
    @shortened_url_service ||= ShortenedUrlService.new
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]

  # GET /urls or /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls or /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy!

    respond_to do |format|
      format.html { redirect_to urls_path, status: :see_other, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:original_url, :shortened_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Url Shortener" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :original_url, style: "display: block" %>
    <%= form.text_field :original_url %>
  </div>

  <div>
    <%= form.label :shortened_url, style: "display: block" %>
    <%= form.text_field :shortened_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <p>
    <strong>Original url:</strong>
    <%= url.original_url %>
  </p>

  <p>
    <strong>Shortened url:</strong>
    <%= url.shortened_url %>
  </p>

</div>

app/views/urls/edit.html.erb
<% content_for :title, "Editing url" %>

<h1>Editing url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Show this url", @url %> |
  <%= link_to "Back to urls", urls_path %>
</div>

app/views/urls/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Urls" %>

<h1>Urls</h1>

<div id="urls">
  <% @urls.each do |url| %>
    <%= render url %>
    <p>
      <%= link_to "Show this url", url %>
    </p>
  <% end %>
</div>

<%= link_to "New url", new_url_path %>

app/views/urls/new.html.erb
<% content_for :title, "New url" %>

<h1>New url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Back to urls", urls_path %>
</div>

app/views/urls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @url %>

<div>
  <%= link_to "Edit this url", edit_url_path(@url) %> |
  <%= link_to "Back to urls", urls_path %>

  <%= button_to "Destroy this url", @url, method: :delete %>
</div>